package cn.sinjinsong.eshop.core.dao.ad;

import cn.sinjinsong.eshop.core.domain.entity.ad.AdDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    int insert(AdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    int insertSelective(AdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    AdDO selectByPrimaryKey(Long product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdDO record);
    
    List<AdDO> findAll();
}