package cn.sinjinsong.eshop.core.domain.entity.product;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductCategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbggenerated
     */
    private Long id;

   
    private String name;
    public ProductCategoryDO(String name){
        this.name = name;
    }
}